server:
  port: 9002

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services: dosb-provider

spring:
  application:
    name: dosb-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        namespace: 42309120-04be-4a42-9b66-62b6ba583c58
        group: DEV_GROUP